version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_RACE=0
    environment:
      - DISCORD_TOKEN=${GO_DISCORD_RECORDER_TOKEN}
      - GUILD_ID=${GO_DISCORD_RECORDER_GUILD}
      - CHANNEL_ID=${GO_DISCORD_RECORDER_CHANNEL}
      - MODEL_PATH=${GO_DISCORD_RECORDER_MODEL_PATH}
      - LISTENING_TO=you
    ports:
      - "8162:8162"
    volumes:
      - ./public:/public
      - ./transcripts:/transcripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              